### PR TITLE
Using ConfigureAwait(false) to avoid context restoration

### LINKED ISSUE #39: Consider using .ConfigureAwait(false) throughout the code
## Description

When awaiting for an async method, by default context is captured and attempted to be restored. Since this is a library, it could be used from UI or non-UI code. W/o specifying `.ConfigureAwait(false)` there will be some overhead of attempting to restore the context. To avoid that, awaited code should explicitly specifying not to restore the context.

> ConfigureAwait provides a means to avoid the default SynchronizationContext capturing behavior; passing false for the flowContext parameter prevents the SynchronizationContext from being used to resume execution after the await.
## Example

Before:

``` c#
await this.SendLinkManager.GetOrCreateAsync(timeoutHelper.RemainingTime());
```

After:

``` c#
await this.SendLinkManager.GetOrCreateAsync(timeoutHelper.RemainingTime()).ConfigureAwait(false);
```

### PR DESCRIPTION
**Pull request by SeanFeldman**
fixes #39

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@serkantkaraca please review

**Comment by SeanFeldman** [comment]
Any comments @serkantkaraca?

**Comment by cesarme** [comment]
Sean, are there benchmarks of how costly not calling .ConfigureAwait(false) is?  I understand less work happens, but what is the real impact we are talking here?

**Comment by SeanFeldman** [comment]
@cesarme perhaps we should have this raised on the [PR thread](https://github.com/Azure/azure-event-hubs-dotnet/issues/39) that is already discussing the issue?

**Comment by cesarme** [comment]
Sure, feel free to reply with benchmarks about it on this thread or the one you mentioned, either way is fine with me.

**Comment by SeanFeldman** [comment]
@cesarme I have not performed the analysis of the performance myself. Please do not focus solely on one aspect of this issue, as there are several. Here's an [MSDN article](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) that goes into explanations about possible performance issues, described as “thousands of paper cuts”. Quoting:

> As asynchronous GUI applications grow larger, you might find many small parts of async methods all using the GUI thread as their context. This can cause sluggishness as responsiveness suffers from “thousands of paper cuts.”

> To mitigate this, await the result of ConfigureAwait whenever you can. The following code snippet illustrates the default context behavior and the use of ConfigureAwait:

```c#
async Task MyMethodAsync()
{
  // Code here runs in the original context.
  await Task.Delay(1000);
  // Code here runs in the original context.
  await Task.Delay(1000).ConfigureAwait(
    continueOnCapturedContext: false);
  // Code here runs without the original
  // context (in this case, on the thread pool).
}
```

> By using ConfigureAwait, you enable a small amount of parallelism: Some asynchronous code can run in parallel with the GUI thread instead of constantly badgering it with bits of work to do.

> Aside from performance, ConfigureAwait has another important aspect: It can **avoid deadlocks.**

**Pull request merged**
