### PR TITLE
Fix EventHubsConnectionStringBuilder ctor crash with SharedAccessSignature

### LINKED ISSUE #288: EPH unstable after when more instances on the dancefloor
## Actual Behavior
1. Hub with 32 partitions
2. One EPH instance, consuming all partitions ok
3. Here comes a new challenger : the 2nd instance start assigning partitions from 0 to 15, while the 1st instance has some lease lost.
4. Then we add a third instance : and then the instances are stealing lease and exchanging partitions endlessly. After several minutes, the balancing is still unstable.

## Expected Behavior
1. When more EPH instance comes, the transition to some other partitions distribution should be smooth and then stable.

## Versions  
- OS platform and version: Azure AKS. Containers base images are microsoft/dotnet:2.0-runtime
- .NET Version: .net core 2.0
- NuGet package version or commit ID: Microsoft.Azure.EventHubs 2.0.0 & Microsoft.Azure.EventHubs.Processor 2.0.1

### PR DESCRIPTION
**Pull request by alexsorokoletov**
When supplying SharedAccessSignature as a parameter

## Description
Fixes #288 (https://github.com/Azure/azure-event-hubs-dotnet/issues/218)

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [x] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [x] If applicable, the public code is properly documented.
- [x] Pull request includes test coverage for the included changes.
- [x] The code builds without any errors.

### CODE REVIEW

**Comment by serkantkaraca** [comment]
Seems we have same PR. Can you add the unit test from my PR. I will approve and merge to dev. Thx!

**Comment by alexsorokoletov** [comment]
@serkantkaraca Thanks, I'm ok if you merge your PR and close this one.

**Comment by serkantkaraca** [comment]
I cannot merge my own w/o approval from another owner. That is why quicker if you add unit tests and I approve as one of the owners :)

**Comment by alexsorokoletov** [comment]
Sure, I will update my later today :)

**Comment by alexsorokoletov** [comment]
@serkantkaraca here you go :)

**Comment by serkantkaraca** [comment]
Merged. Thx a lot!

**Pull request merged**
