### PR TITLE
Introduced factory method in EventData class

### PR DESCRIPTION
**Pull request by kamil-mrzyglod**
## Description
It references issue #24 in which there's a need to ease creation of `EventData` object with SystemProperties populated for testing purpose.

Note that there's a possibility to introduce a `protected static` method, which could be used only from within derived class - what could hide it by default - but I decided, that this complicates such a simple tasks and creates too much overhead. I'm eager to discuss alternatives however.

This checklist is used to make sure that common guidelines for a pull request are followed.

- [X ] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [ X] Title of the pull request is clear and informative.
- [ X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [ X] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [ X] If applicable, the public code is properly documented.
- [ X] Pull request includes test coverage for the included changes.
- [ ]X The code builds without any errors.

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by jtaubensee** [comment]
Hi @kamil-mrzyglod - Thank you for you contribution, but this isn't something that we would like to move forward with at the moment. We would prefer not to have methods on a class that are only to be used for testing. Instead, our team is planning on properly abstracting the components, and using interfaces to allow easy mocking for test purposes. Please stay tuned for that...

**Comment by matpatte** [comment]
Has any progress been made on this?  I could really use this!

**Comment by serkantkaraca** [comment]
EventData.SystemProperties is now public settable.

https://github.com/Azure/azure-sdk-for-net/blob/5d37e27fd4f8e5bb7fdf998aa7314c3406f72bba/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventData.cs#L72

**Comment by EngSayed** [comment]
> EventData.SystemProperties is now public settable.
> 
> https://github.com/Azure/azure-sdk-for-net/blob/5d37e27fd4f8e5bb7fdf998aa7314c3406f72bba/sdk/eventhub/Microsoft.Azure.EventHubs/src/EventData.cs#L72

New Azure SDK uses Azure.Messaging.EventHubs.EventData which does not have a public setter for SystemProperties. Is there a solution for that? 
EventData is not mockable

**Pull request closed without merging**
