### PR TITLE
Capture xunit output

### PR DESCRIPTION
**Pull request by SeanFeldman**
works for failed tests

image

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@serkantkaraca please review

**Comment by serkantkaraca** [comment]
:shipit:

**Comment by SeanFeldman** [comment]
@serkantkaraca rebased and updated. Had some conflicts to resolve. All tests are green, so assuming all good :)

**Comment by SeanFeldman** [comment]
yay! 🎉

**Pull request merged**
