### PR TITLE
Fix Build for Plugin_without_ShouldContinueOnException_should_throw Failing

### PR DESCRIPTION
**Pull request by davidrevoledo**
## Description
@serkantkaraca for this
https://github.com/Azure/azure-event-hubs-dotnet/pull/324

Here the client create other send and lose the Plugins, 
I've copy them in the method you can see in the change, what do you think of this approach, any other better way to do that ? 

https://github.com/Azure/azure-event-hubs-dotnet/blob/4fc6c60288c1c38dc89aca8424ae2a4c24ecfe25/src/Microsoft.Azure.EventHubs/EventHubClient.cs#L51

This checklist is used to make sure that common guidelines for a pull request are followed.

- [x] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [x] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [x] If applicable, the public code is properly documented.
- [x] Pull request includes test coverage for the included changes.
- [x] The code builds without any errors.

### CODE REVIEW

**Comment by davidrevoledo** [comment]
As the Sender is getting the reference as the first param for the Ctor we can also add some init method here
https://github.com/Azure/azure-event-hubs-dotnet/blob/61bdc55a5b40c8c9737c71646041bfb70d17c922/src/Microsoft.Azure.EventHubs/Amqp/AmqpEventDataSender.cs#L18

To copy internally plugins and avoid the code in the `OnCreateEventSender` avoiding future problems if there is a new one

**Comment by serkantkaraca** [comment]
This time Multiple_plugins_should_run_in_order fails.

**Comment by serkantkaraca** [comment]
One of the plugin tests keep failing in dev branch. Can you take a look?

https://ci.appveyor.com/project/serkantkaraca/azure-event-hubs-dotnet/branch/dev/job/4j2aqhiu403e357k/tests

**Comment by davidrevoledo** [comment]
wow really last time were all running ok, sure in a few minutes will finish something and will take a look @serkantkaraca

**Comment by davidrevoledo** [comment]
@serkantkaraca as currently is a concurrent dictionary and not a list it does not make sense that the plugin runs in order, as any thread can register plugins on the fly, so make sense just remove that test, are you agree ? 

It's because the test force to run in order,

**Comment by serkantkaraca** [comment]
Absolutely makes sense. Let's remove it.

Besides, anyone needing plugin order can combine 2 plugins and assure the order. There is no need to provide this type of guarantee in the client.

**Comment by davidrevoledo** [comment]
well in some case it'd be needed if you have some pipeline and you need to ensure 

plugin 1 run first if plugin 2 break w/o 1

but we can wait until that moment to think in something more complex, it's very easily to change. 

a Priority int to the plugin like Firewall IP rules, or locking the register and save them with order .

We can check that in the future when will be needed.

**Pull request merged**
