### PR TITLE
Make partition context public for test-ability.

### PR DESCRIPTION
**Pull request by serkantkaraca**
## Description

This checklist is used to make sure that common guidelines for a pull request are followed.

- [ ] **I have read the [contribution guidelines](./CONTRIBUTING.md).**
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR.
- [ ] The pull request does not introduce breaking changes (unless a major version change occurs in the assembly and module).
- [ ] If applicable, the public code is properly documented.
- [ ] Pull request includes test coverage for the included changes.
- [ ] The code builds without any errors.

### CODE REVIEW

**Comment by NatanaelLemos** [comment]
Hi @serkantkaraca, thanks for making this change.
Just a quick check, I see that this Pull Request has 5 days. Is it waiting for my approval?

**Review by JamesBirdsall — APPROVED** [review]

**Comment by farhad-taran** [comment]
@JamesBirdsall Has this been released to nuget?

I am still seeing this for microsoft.azure.eventhubs.processor v3:

**Comment by JamesBirdsall** [comment]
@serkantkaraca is the releaser for this client.

**Comment by serkantkaraca** [comment]
This will be part of next release.

**Pull request merged**
