### PR TITLE
Moving samples to the azure-event-hubs repo

### PR DESCRIPTION
**Pull request by sethmanheim**
cc @jtaubensee

### CODE REVIEW

**Comment by jtaubensee** [comment]
@sethmanheim - Can you update the links on the main readme? Also open the solution in VS and remove the projects. It should update the .sln file.

**Comment by sethmanheim** [comment]
Wait, what? Didn't I do that already?

**Comment by sethmanheim** [comment]
@jtaubensee Not exactly sure what you're asking for here. There is no main readme in this repo.

**Comment by jtaubensee** [comment]
So the .sln file here: https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/Microsoft.Azure.EventHubs.sln

Will need to have this removed:
```
Project("{2150E333-8FDC-42A3-9474-1A3956D46DE8}") = "samples", "samples", "{188550D8-80F0-410D-AECA-BC3C1F96CF95}"
EndProject
Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "SampleSender", "samples\SampleSender\SampleSender.xproj", "{940BCA4A-B154-4667-8A03-57E6B689866D}"
EndProject
Project("{8BB2217D-0F2D-49D1-97BC-3654ED321F3B}") = "SampleEphReceiver", "samples\SampleEphReceiver\SampleEphReceiver.xproj", "{679DFCC5-76BD-4725-A51E-AFBB01565401}"
EndProject
```

And this readme for the repo, has links to the samples...

https://github.com/Azure/azure-event-hubs-dotnet/blob/dev/readme.md

**Comment by jtaubensee** [comment]
Thanks @sethmanheim. We will hold off on this until docs.microsoft.com is updated.

**Comment by serkantkaraca** [comment]
:shipit:

**Comment by sethmanheim** [comment]
Thanks guys. @jtaubensee if you agree, I'm can sign off on https://github.com/Microsoft/azure-docs-pr/pull/7598, so we can probably merge this one at the same time.

**Comment by jtaubensee** [comment]
Yep, please merge the other one, but we cant merge this until the other changes are published.

**Pull request merged**
